baseURL                 = "/"
disablePathToLower      = false
languageCode            = "en"
title                   = "gbbns.co"
metaDataFormat          = "yaml"
enableRobotsTXT         = true
watch                   = true
buildDrafts             = false
buildFuture             = false
pluralizeListTitles		= false

[blackfriday]
    laxHtmlBlocks       = true

[permalinks]
    articles            = "/writing/:year/:month/:day/:slug/"
    notes               = "notes/:slug"

[taxonomies]
    tag                 = "tags"
    category            = "categories"
	writings			= "writing"

[[menu.main]]
  name   = "About"
  url    = "/about/"
  weight = 1

[[menu.main]]
  name   = "Writing"
  url    = "/writing/"
  weight = 2

[[menu.main]]
  name   = "Speaking"
  url    = "/speaking/"
  weight = 3

[[menu.main]]
  name   = "Contact"
  url    = "/contact/"
  weight = 4

[[menu.footer]]
  name   = "Colophon"
  url    = "/colophon/"
  weight = 1

[[menu.footer]]
  name   = "Now"
  url    = "/now/"
  weight = 2

[[menu.footer]]
  name   = "Uses"
  url    = "/uses/"
  weight = 3

[[menu.footer]]
  name   = "Categories"
  url    = "/categories/"
  weight = 4

[[menu.footer]]
  name   = "Tags"
  url    = "/tags/"
  weight = 5



# Site settings
[params]
    title               = "UX Technologist"
    subTitle            = "Front end meets UX"
    siteTitle           = "Front end developer & UX technologist based in Blackpool // Manchester"
	siteURL				= "gbbns.co"
    email               = "chris@gbbns.co"
    description         = "Chris Gibbons // Front End Developer // UX Technologist based in Lancashire, UK."
    author              = "Chris Gibbons"
    metaDescription     = "Chris is a Principle Front end developer & UX technologist based in Blackpool, Lancashire & Manchester, UK. He build's flexible responsive and accessible websites and bakes a smashing cake."
    metaTitle           = "Chris Gibbons // Principle Front end developer & UX technologist based in Blackpool, Lancashire & Manchester, UK."
    metaKeywords        = "Chris Gibbons, chris, gibbons, gbbns, blackpool, lancashire,england, uk, united kingdom, html, css, xhtml, web standards, accessibility, javascript"
    twitter             = "_gbbns"
    github              = "gbbns"
    linkedin            = "gbbns"
    lastfm              = "jibubo"
    flickr              = "jibubo"
    insta               = "_gbbns"
    vsco                = "jibubo"
    fiveHundredPx       = "gbbns"
